const IG='https://ig.me/m/posters_wallah';
const products=[
{id:1,name:'BMW Performance',cat:'Cars',price:59,img:'https://images.unsplash.com/photo-1734940521812-995c5ef6dcf0?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:2,name:'BMW Street Night',cat:'Cars',price:59,img:'https://images.unsplash.com/photo-1668918294568-0f21e7aa1136?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:3,name:'Gaming Neon',cat:'Gaming',price:59,img:'https://images.unsplash.com/photo-1700085663917-73fa5feea8a4?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:4,name:'Arcade Energy',cat:'Gaming',price:59,img:'https://images.unsplash.com/photo-1700085663931-a8886b1d4725?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:5,name:'Gaming Workspace',cat:'Gaming',price:119,img:'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:6,name:'Night Drive',cat:'Aesthetic',price:119,img:'https://images.unsplash.com/photo-1668918294568-0f21e7aa1136?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:7,name:'Premium Car Wall',cat:'Cars',price:199,img:'https://images.unsplash.com/photo-1734940521812-995c5ef6dcf0?auto=format&fit=crop&fm=jpg&q=82&w=1200'},
{id:8,name:'Neon Arcade',cat:'Aesthetic',price:119,img:'https://images.unsplash.com/photo-1700085663917-73fa5feea8a4?auto=format&fit=crop&fm=jpg&q=82&w=1200'}
];
let cart=JSON.parse(localStorage.getItem('pw-cart')||'[]');
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderProducts(filter='All',query=''){const list=products.filter(p=>(filter==='All'||p.cat===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));$('#products').innerHTML=list.map(p=>`<article class="product"><div class="product-img"><img loading="lazy" src="${p.img}" alt="${p.name} poster"><span class="product-tag">${p.cat}</span></div><div class="product-info"><small>POSTERS WALLAH</small><h3>${p.name}</h3><div class="product-row"><span class="price">₹${p.price}</span><button class="add" onclick="add(${p.id})">ADD TO CART</button></div></div></article>`).join('')||'<p style="color:#777">No posters found.</p>'}
function save(){localStorage.setItem('pw-cart',JSON.stringify(cart))}
function add(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();renderCart();toast('Added to cart');}
function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save();renderCart()}
function renderCart(){const count=cart.reduce((a,b)=>a+b.qty,0);$('#cartCount').textContent=count;const total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);$('#cartTotal').textContent='₹'+total;$('#cartItems').innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-item"><img src="${p.img}"><div><h4>${p.name}</h4><p>${p.cat} • ₹${p.price} each</p><div class="qty"><button onclick="change(${p.id},-1)">−</button><span>${i.qty}</span><button onclick="change(${p.id},1)">+</button></div></div><b>₹${p.price*i.qty}</b></div>`}).join(''):'<p style="color:#777;text-align:center;padding:40px 0">Your cart is empty.</p>'}
function orderText(){let lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `• ${p.name} — ${p.cat} — Qty ${i.qty} — ₹${p.price*i.qty}`});let total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);return `Hi Posters Wallah! 👋\n\nI want to order:\n${lines.join('\n')}\n\nTotal: ₹${total}\n\nPlease confirm availability and delivery details.`}
async function instagramOrder(){if(!cart.length){toast('Add a poster first');return}const text=orderText();try{await navigator.clipboard.writeText(text);toast('Order copied — Instagram DM is opening');setTimeout(()=>window.open(IG,'_blank'),500)}catch{window.open(IG,'_blank');toast('Instagram opened — send your order details')}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});
$$('.collections article').forEach(c=>c.onclick=()=>{const f=c.dataset.filter;$$('.filters button').forEach(x=>x.classList.toggle('active',x.dataset.filter===f));renderProducts(f);location.hash='shop'});
$('#cartBtn').onclick=()=>{$('#cart').classList.add('open');$('#overlay').classList.add('show')};$('#closeCart').onclick=()=>{$('#cart').classList.remove('open');$('#overlay').classList.remove('show')};$('#overlay').onclick=()=>{$('#cart').classList.remove('open');$('#overlay').classList.remove('show')};$('#instagramOrder').onclick=instagramOrder;
$('#customDm').onclick=e=>{e.preventDefault();const text=`Hi Posters Wallah! 👋\n\nI want a CUSTOM POSTER.\n\nSize: \nQuantity: \nTheme: \nCustom text: \n\nI will send my reference image here. Please share the price and details.`;navigator.clipboard?.writeText(text);window.open(IG,'_blank')};
$('#searchBtn').onclick=()=>$('#search').classList.add('open');$('#closeSearch').onclick=()=>$('#search').classList.remove('open');$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase();$('#searchResults').innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)).map(p=>`<div class="search-result"><b>${p.name}</b><br><small>${p.cat} • ₹${p.price}</small></div>`).join('')};
$('#hamb').onclick=()=>{const nav=$('.nav nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='65px';nav.style.left='10px';nav.style.right='10px';nav.style.padding='18px';nav.style.background='#111317';nav.style.border='1px solid #fff2';nav.style.borderRadius='14px';nav.style.flexDirection='column'};
renderProducts();renderCart();
